config/routes.rb
Classifieds::Application.routes.draw do

  resources :pages, only: [:index, :create]
  resources :alerts, except: [:show] do
    collection do
      post :search
    end
  end

  root :to => 'pages#index'
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :category
  attr_accessible :email, :keywords, :category_id

  validates :email, presence: true, uniqueness: true
  validates :keywords, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :classifieds, dependent: :destroy
  has_many :alerts, dependent: :destroy
  belongs_to :section
  attr_accessible :name, :url, :section_id

  default_scope order('id')

  validates :name, presence: true
  validates :url, presence: true
end

app/models/classified.rb
class Classified < ActiveRecord::Base

  belongs_to :category

  attr_accessible :content

  default_scope order('id')

  validates :content, presence: true
  validates :content, uniqueness: true

  def self.searchable_language
    'spanish'
  end
end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
  has_many :sections, dependent: :destroy
  attr_accessible :name, :url

  validates :name, presence: true, uniqueness: true
  validates :url, presence: true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :categories, dependent: :destroy
  belongs_to :newspaper
  attr_accessible :name, :newspaper_id

  validates :name, presence: true
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  def index
    render layout: false
  end

  def new
    @alert = Alert.new
    render layout: false
  end

  def create
    @alert = Alert.new(params[:alert])
    if @alert.save
      flash.now[:notice] = "Alerta creada exitosamente"
    else
      flash.now[:error] = @alert.errors.full_messages
    end
  end

  def edit
    @alert = Alert.find(params[:id])
    render layout: false
  end

  def update
    @alert = Alert.find(params[:id])
    if @alert.update_attributes(params[:alert])
      flash.now[:notice] = "Alerta actualizada exitosamente"
    else
      flash.now[:error] = @alert.errors.full_messages
    end
  end

  def destroy
    @alert = Alert.find(params[:id])
    if @alert.destroy
      flash.now[:error] = "Alerta Eliminada"
    else
      flash.now[:error] = @alert.errors.full_messages
    end
  end

  def search
    @alert = Alert.find_by_email(params[:email])
    flash.now[:error] = "No existes alertas" if @alert.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @classifieds = []
  end

  def create
    @classifieds = Classified.basic_search(content: params[:keyword]) if params[:keyword].present?
    @classifieds = Classified.where(category_id: params[:category]) if params[:category].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alerts/create.js.erb
$('#flashes').html("<%= escape_javascript(bootstrap_flash)%>");
<% if @alert.persisted? %>
  setTimeout(function(){$('#modal-window').modal('hide');},1000);
<% end %>

app/views/alerts/destroy.js.erb
$('#flashes').html("<%= escape_javascript(bootstrap_flash)%>");
<% if @alert.destroyed? %>
  setTimeout(function(){$('#modal-window').modal('hide');},1000);
<% end %>

app/views/alerts/edit.html.haml
= form_for @alert, remote: true, html: {class: "form-horizontal"} do |f|
  #flashes
    = bootstrap_flash
  .control-group
    = f.label :email, class: "control-label"
    .controls
      = f.email_field :email, placeholder: 'Digite su Email'
  .control-group
    = f.label :keywords, class: "control-label"
    .controls
      = f.text_field :keywords, class: "input-tag"
  %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Cerrar
  = link_to "Eliminar", alert_path(@alert), class: "btn btn-danger", method: :delete, remote: true
  = f.submit "Actualizar", class: "btn btn-primary pull-right"

:javascript
  $(function(){
    $('.input-tag').tag({placeholder: "Palabras clave, delimitado por coma"});
  });

app/views/alerts/index.html.haml
= form_tag search_alerts_path, remote: true, class: "form-horizontal" do
  #flashes
    = bootstrap_flash
  .control-group
    = label_tag :email, "Email", class: "control-label"
    .controls
      = email_field_tag :email, nil, placeholder: 'Digite su Email'
  %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Cerrar
  = submit_tag "Buscar Alerta", class: "btn btn-primary pull-right"

app/views/alerts/new.html.haml
= form_for @alert, remote: true, html: {class: "form-horizontal"} do |f|
  #flashes
    = bootstrap_flash
  .control-group
    = f.label :email, class: "control-label"
    .controls
      = f.email_field :email, placeholder: 'Digite su Email'
  .control-group
    = f.label :keywords, class: "control-label"
    .controls
      = f.text_field :keywords, class: "input-tag"
  %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Cerrar
  = f.submit "Guardar", class: "btn btn-primary pull-right"

:javascript
  $(function(){
    $('.input-tag').tag({placeholder: "Palabras clave, delimitado por coma"});
  });

app/views/alerts/search.js.erb
<% if @alert.present? %>
  $('#modal-window').modal("hide")
  setTimeout(function(){
    $('#modal-window').modal({remote: "<%= edit_alert_path(@alert) %>"})
  },800);
<% else %>
  $('#flashes').html("<%= escape_javascript(bootstrap_flash)%>");
<% end %>

app/views/alerts/update.js.erb
$('#flashes').html("<%= escape_javascript(bootstrap_flash)%>");
<% if @alert.persisted? %>
  setTimeout(function(){$('#modal-window').modal('hide');},1000);
<% end %>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  = render "shared/head"
  %body
    = render "shared/header"
    .container-fluid
      .row-fluid
        .span3
          = render "shared/sidebar_menu"
        .span9
          = bootstrap_flash
          = yield
      .loading.hide
      .modal-template
      = render "shared/footer"
    = render "shared/modal"
    = javascript_include_tag "application"

app/views/pages/_list.html.haml
- if classifieds.any?
  %ol
    -classifieds.each do |classified|
      %li
        = classified.content
        %hr
- else
  %p No hay Clasificados que mostrar

app/views/pages/create.js.erb
$('.result-list').html("<%=j(render 'list', classifieds: @classifieds) %>");

app/views/pages/index.html.haml
%hr
.result-list
  = render "list", classifieds: @classifieds

app/views/shared/_footer.html.haml
%footer
  %p
    Ni derechos o izquierdos :P, el código lo puedes ver en
    %a{:href => "https://github.com/theharq/classifieds"} https://github.com/theharq/classifieds

app/views/shared/_head.html.haml
%head
  %meta(charset="utf-8")
  %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  %title= content_for?(:title) ? yield(:title) : "Classifieds"
  = csrf_meta_tags
  / Le HTML5 shim, for IE6-8 support of HTML elements
  /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
  = stylesheet_link_tag "application", :media => "all"
  %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
  %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
  %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
  %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
  / %link(href="favicon.ico" rel="shortcut icon")

app/views/shared/_header.html.haml
.navbar.navbar-fluid-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Clasificados", root_path, class: "brand"
      .container.nav-collapse
        %ul.nav
          %li= link_to "Crear Alerta", new_alert_path, "data-target" => "#modal-window", "data-toggle" => "modal"
          %li= link_to "Editar Alerta", alerts_path, "data-target" => "#modal-window", "data-toggle" => "modal"
        = form_tag pages_path, remote: true, class: "navbar-search pull-right" do
          %input.search-query{placeholder: "Ej: Apartaestudio", type: "text", name: "keyword"}
          %button.btn{type: "submit"} Buscar

app/views/shared/_modal.html.haml
#modal-window.modal.hide.fade{role: "dialog"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3 Alertas
  .modal-body

app/views/shared/_sidebar_menu.html.haml
.well.sidebar-nav
  %ul.nav.nav-list
    - Section.all.each do |section|
      %li.nav-header= section.name
      - section.categories.each do |category|
        %li= link_to category.name, pages_path(category: category), method: :post, remote: true